### ISSUE TITLE
scoring-bmis

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#108]
**Scoring Instructions:**
Four summed scores:
`bmis_scrdVal_sX_rX_eX` (sum of {1, 2, 5, 6, 11, 13, 14, 16} + reversed sum of {3, 4, 7, 8, 9, 10, 12, 15})
`bmis_scrdAro_sX_rX_eX` (sum of {1, 5, 3, 7, 8, 11, 12, 14, 15, 16} + reversed sum of {4, 13})
`bmis_scrdTird_sX_rX_eX` (sum of {1, 5, 11, 14, 16} + reversed sum of {4, 9})
`bmis_scrdRlx_sX_rX_eX` (sum of {3, 7, 8, 12, 15} + reversed sum of {13})

To reverse scores, 1>4, 2>3, 3>2, 4>1.  That is, if the participant chose "1" for a question that is being reversed in a particular score, then the script should use the value "4".

_To calculate partials:_
Calculate percentage complete:
`bmis_percTot_sX_rX_eX`
If equal to 1, compute score; otherwise, do not compute score.

**Done Defined:**
- bmis added to the scoring script
- bmis added to repo (PDF, REDCap zip, REDCap PDF, readme)

**Comment by jessb0t** [comment]
@anaNDClab Would you please check my work on this one?

[scoring instructions](https://app.zenhub.com/files/362482923/bc1c9920-7e18-4274-8e0c-6e6312394d07/download)

**Comment by anaNDClab** [comment]
@jessb0t This scoring makes sense to me! I like how you explained reverse scoring. However, I think that for the last sum score (the Negative-Relaxed scale) you are missing a number to calculate the score. Currently, you have “bmis_scrdRlx_sX_rX_eX (sum of {3, 8, 12, 15} + reversed sum of {13}). ” However, you are missing the Gloomy response, which is question #7. Therefore, I think the last sum score scoring instruction should look like this:
 “bmis_scrdRlx_sX_rX_eX (sum of {3, 7, 8, 12, 15} + reversed sum of {13}).”
 Let me know if this is a mistake.

**Comment by jessb0t** [comment]
Thank you so much, @anaNDClab !  You were 100% correct.  I adjusted the issue Description above with this correction! :raised_hands:
