### ISSUE TITLE
testing-bpsqi

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#111]

**Comment by jessb0t** [comment]
@blope118 I just tested the initial BPSQI output.  Here are my notes:
1. I think we made a typo in the instructions.  The SLP subscore should look at item 3 (how long does it take you to fall asleep?) not item 2.  I corrected it #110.  Apologies!
2. For participant 150003 on `bpsqi_s1_r1_e1`, I end up with a problem because I have to divide by 0.  The script doesn't seem to hit this hurdle.  Wondering how it is handling 900/(24-10+10)?

**Comment by blope118** [comment]
@jessb0t Hello,
1.) I will make the adjustment to surveys.json and output again

**Comment by jessb0t** [comment]
Tested clean!

**Comment by anaNDClab** [comment]
The scores calculated in the input file match the scores found in the output file!
