### ISSUE TITLE
testing-panas (full)

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#117]

**Comment by jessb0t** [comment]
PANASNOW output not correct. Rows with no input data are outputting a score. Communicated with @blope118 via Slack.

**Comment by jessb0t** [comment]
See notes on #119, tested at the same time.  Resolved.

**Comment by jessb0t** [comment]
Tested clean!

**Comment by anaNDClab** [comment]
The scores calculated in the input file match the scores found in the output file!
