### ISSUE TITLE
Scoring bug for aq10

### ISSUE THREAD

**Issue by F-said** [NDCLab/instruments#124]
> Check column aq10_scrd_total_s1_r1_e1 in output.  All 2s!
> The main ADEXI (adexi_XXX_s1_r1_e1) looks good.  But adexi_b_perc_total_s1_r1_e1 is coming through with zeros and adexi_b_scrd_total_s1_r1_e1 is totally blank. :confused:

Tied in to products scoring

**Comment by jessb0t** [comment]
Tested by @jessb0t and @anaNDClab !
