### ISSUE TITLE
changing readmes to read "folder" or "subfolder" instead of repository?

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/instruments#131]
Issue/question: My understanding is that the term "repository" is reserved for the larger folder that houses various branches, whereas folders/subfolders/directories inside a repository are not called repositories.

If my understanding above is correct, then a (low priority) fix is to adjust the readmes for each instrument folder to change the term "repository" to something else (i.e., folder, subfolder, or directory).

**Comment by georgebuzzell** [comment]
Note, posting this as an issue so as not to hold up the current pr

**Comment by jessb0t** [comment]
@georgebuzzell I'm not sure I understand.  I believe that "instruments" is a repository by the GitHub definitions.  [Here](https://docs.github.com/en/repositories) is an example.  Let me know if I am misunderstanding the question/suggestion!

**Comment by georgebuzzell** [comment]
@jessb0t Sorry, I am not sure, but going back and looking at the readme, I think this comment was from me reading the following section too quickly. That is, I think I read the reference to "repo" in the last line as referring to a given subfolder that is referenced at the top. But, on re-reading I see no error here. Closing the issue.

![image](https://user-images.githubusercontent.com/71228105/153744298-c6f9a3db-d918-43ee-a3fa-854bea655e80.png)
