### ISSUE TITLE
follow-up: ari average score

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#160]
We are currently calculating a true average for this subscore.  The instructions are unclear: they offer a lot of specificity but never indicate that the average score should be rounded (and, if rounded, in which direction).  However, they also imply that the output of the average score is only (0, 1, 2).

![image.png](https://images.zenhubusercontent.com/6054b276e1e4e5cb58c9e577/ed62f9ba-17b0-4c2f-ac46-33417da48f42)

**Comment by jessb0t** [comment]
@georgebuzzell Could you take a look at this issue when you have a moment and let us know your thoughts?  Thank you!

**Comment by georgebuzzell** [comment]
@jessb0t agree this is confusing wording here.

I looked at some other papers, and I think that we will most likely use the "total raw score" (sum of items) anyways, so i dont think we should worry too much about that average total score. Please move ahead by computing:

1. the "total raw score" (sum)
2. the prorated score (which is essentially a prorated sum, rounded to nearest whole number, that is only calculated if  a single item (but not more) is missing). 

Please just leave off computation of the average total score and put in the readme for this instrument that it is currently not computed

**Comment by jessb0t** [comment]
Got it!  Thanks @georgebuzzell !

**Comment by jessb0t** [comment]
Tested clean!
