### ISSUE TITLE
adexi-rescore to average

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#178]
In preparing scoring notes for the TEXI, it came to light that the ADEXI uses an average score, not a sum score as initially assumed.  Details available in the main paper:

![image.png](https://images.zenhubusercontent.com/6054b276e1e4e5cb58c9e577/c8fa0b8e-b543-44ea-a8d5-c8106228cef2)

![image.png](https://images.zenhubusercontent.com/6054b276e1e4e5cb58c9e577/55b589e7-c2de-4d69-9b80-b4fa70f873de)

Script to be updated so that output is an average score with standard threshold of 80%.

**Comment by jessb0t** [comment]
Tested clean!

**Comment by anaNDClab** [comment]
The scores I found in the input file match the scores found in the output file!
