### ISSUE TITLE
scoring-ari

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#34]
**Scoring Instructions:**
Two total scores:
`ari_scored-raw_sx_rx_ex` (sum of: 1-6)
`ari_scored-avg_sx_rx_ex` (average of: 1-6)

_To calculate partials:_
Calculate percentage complete (0-1) based on questions 1-6 only (ignore question 7):
`ari_per-complete_sx_rx_ex`

If greater than 0.83 but less than 1, compute prorated score instead of total scores:
`ari_scored-prorat_sx_rx_ex`
1. Sum together items 1-6.
2. Multiply this number by 6.
3. Divide by 5.
4. Round to the nearest whole number.

**Done Defined:**
- ari added to the scoring script on dev-script (OP/FS)
- ari added to dev-uploads (PDF, REDCap zip, readme) (JA/ALN)

**Comment by georgebuzzell** [comment]
@jessb0t yes and no. :)

All of what you have above for the computed scores listed is correct. I would just add that we also want to pass item 7 as its own "score" in the scored output

**Comment by jessb0t** [comment]
@georgebuzzell Can you clarify what you mean by that?  The original response for item 7 will remain in the output file, so it seems that the scoring script could just leave it be, then?

**Comment by georgebuzzell** [comment]
Ah, yes, good point. Then that is fine! @jessb0t
