### ISSUE TITLE
scoring-bfne

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#38]
**Scoring Instructions:**
Single, simple summed score:
`bfne_scrdTot_sx_rx_ex`

_To calculate partials:_
Calculate percentage complete:
`bfne_percTot_sx_rx_ex`

If equal to 1, compute score; otherwise, do not compute score.

**Done Defined:**
- bfne2 added to the scoring script
- bfne2 added to repo (PDF, REDCap zip, REDCap PDF, readme)

**Comment by jessb0t** [comment]
@georgebuzzell I am unable to find any scoring instructions for the BFNE (Carleton et al., 2007).  Scoring instructions are available for the original BFNE (Leary, 1983). The questions seem the same except that they have been reworded to avoid the reverse scoring.  So I presume that this is a simple sum score?  I have marked the scoring instructions accordingly, but would value your confirmation.

![image.png](https://images.zenhubusercontent.com/6054b276e1e4e5cb58c9e577/dae27458-c029-4661-b9e9-eea09955656a)

**Comment by georgebuzzell** [comment]
@jessb0t yes! correct; just a sum score! thank you for checking!

**Comment by jessb0t** [comment]
Thank you, @georgebuzzell !  @SDOsmany: I updated the description, so this is a simple summed score, nothing fancy (and no reverse coding because the instrument already adjusted for that). :)
