### ISSUE TITLE
scoring-ADEXI (part 1)

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#4]
Based on appropriate ADEXI scoring system, flesh out scoring script for ADEXI to add three columns:
1. Working Memory subscale score
2. Inhibition subscale score
3. Total score

@georgebuzzell : Thoughts on how we should name these new variables in the output CSV?  Initial proposal:
adexi_total-score
adexi_subscore-wm
adexi_subscore-inh

**Comment by georgebuzzell** [comment]
cross-posting from slack!

For the computed variable names, I would suggest some slight variations on what you all have proposed, to keep in line with our prior naming conventions, I suggest the following (and in this order):

adexi_timestamp_s1_r1_e1, adexi_complete_s1_r1_e1, adexi_scored-total_s1_r1_e1, adexi_scored-INH_s1_r1_e1, adexi_scored-wm_s1_r1_e1

I think naming them in this way would more closely align with our naming conventions. However, let me know if I am missing something or you have additional/alternative thoughts.

**Comment by jessb0t** [comment]
@georgebuzzell Thank you!

@SDOsmany and @F-said, updated below for clarity!

**Correction:**
timestamp: use automatic column name from REDCap
complete: use automatic column name from REDCap

**Scored Columns:**
adexi_scored-total_s1_r1_e1
adexi_scored-inh_s1_r1_e1
adexi_scored-wm_s1_r1_e1

**Comment by jessb0t** [comment]
@georgebuzzell

@SDOsmany mentioned that you had requested additional columns for partial scoring.  I assume that this is the "percentage complete" information?  If I am correct in this assumption, I presume that we should add for ADEXI:

adexi_per-complete-total_s1_r1_e1
adexi_per-complete-inh_s1_r1_e1
adexi_per-complete-wm_s1_r1_e1

Where each column is a number from 0-1 indicating the percentage of items necessary for scoring of the overall instrument or one of its subscores.  (So, for instance, wm could be 1 for 100% completion and we would proceed with scoring that subscore, but if inh were 0.8, we would not calculate either a inh subscore nor a total score given that the ADEXI is calculated by summing.)

**Comment by georgebuzzell** [comment]
Yes, perfect @jessb0t!!

And just to clarify, given that adexi uses sum scores, you would not compute scores if even one item is missing for a given score. You only compute in the presence of missing data for avg scores, and then, only if the amount of items complete for that score are greater than or equal to 80%

**Comment by jessb0t** [comment]
Thank you, @georgebuzzell.  If one item is missing from ADEXI, this would prevent us from computing a total score and the associated subscore, **but not from computing the other subscore for which the participant answered all associated questions**, right?

**Comment by georgebuzzell** [comment]
@jessb0t yes, correct!

**Comment by jessb0t** [comment]
Closing with #13.
