### ISSUE TITLE
scoring-hvs

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#44]
`edshvs_scrdHvsEver_sx_rx_ex` (count of questions 8-13 with response >0)
`edshvs_scrdHvsFreq_sx_rx_ex` (sum of questions 8-13)

**Comment by jessb0t** [comment]
@georgebuzzell Please reference conversation on #40. I have added the three scoring mechanisms that we discussed to the description of that issue. They are, in effect:
- ever/never (count of all answers >0)
- frequency (sum of Likert answers)
- chronicity (extrapolation of Likert answers to "times per year", which is then summed)

We can easily do the first two for the HVS, as well.  However, because we used the version of HVS that has a different set of possible answers, we cannot automatically extend the chronicity scoring of the EDS over to the HDS.  Would you like us to try to come up with a variation for chronicity on the HVS at this time, or simply limit to the ever/never and frequency scoring options?

**Comment by georgebuzzell** [comment]
@jessb0t fine with me to just limit to the first two for the foreseeable future!
