### ISSUE TITLE
scoring-idea

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#47]
**Scoring Instructions:**
No total score.  Six subscores:
`idea_scored-idex_sx_rx_ex` (average of: 12, 23, 24, 25, 26, 27, 28)
`idea_scored-poss_sx_rx_ex` (average of: 1, 2, 4, 16, 21)
`idea_scored-neg_sx_rx_ex` (average of: 3, 6, 8, 9, 11, 17, 20)
`idea_scored-other_sx_rx_ex` (average of: 13, 14, 18)
`idea_scored-self_sx_rx_ex` (average of: 5, 7, 10, 15, 19, 22)
`idea_scored-btwn_sx_rx_ex` (average of: 29, 30, 31)

_To calculate partials:_
Calculate percentage complete (0-1) for each subscore:
`idea_perc-idex_sx_rx_ex`
`idea_perc-poss_sx_rx_ex`
`idea_perc-neg_sx_rx_ex`
`idea_perc-other_sx_rx_ex`
`idea_perc-self_sx_rx_ex`
`idea_perc-btwn_sx_rx_ex`

If greater than or equal to 0.8, compute subscore.  If less than 0.8, do not compute subscore.

**Done Defined:**
- idea added to the scoring script on dev-script (OP/FS)
- idea added to dev-uploads (PDF, REDCap zip, readme) (JA/ALN)

**Comment by georgebuzzell** [comment]
looks good, @jessb0t !
