### ISSUE TITLE
scoring-ierq

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#49]
**Scoring Instructions:**
No total score.  Four subscores:
`ierq_scored-enh_sx_rx_ex` (sum of: 3, 6, 8, 13, 18)
`ierq_scored-per_sx_rx_ex` (sum of: 2, 7, 10, 14, 17)
`ierq_scored-soo_sx_rx_ex` (sum of: 4, 9, 12, 16, 19)
`ierq_scored-mod_sx_rx_ex` (sum of: 1, 5, 11, 15, 20)

_To calculate partials:_
Calculate percentage complete (0-1) for each subscore:
`ierq_per-complete-enh_sx_rx_ex`
`ierq_per-complete-per_sx_rx_ex`
`ierq_per-complete-soo_sx_rx_ex`
`ierq_per-complete-mod_sx_rx_ex`

If equal to 1, compute subscore.  If less than 1, do not compute subscore.

**Done Defined:**
- ierq added to the scoring script on dev-script (OP/FS)
- ierq added to dev-uploads (PDF, REDCap zip, readme) (JA/ALN)

**Comment by georgebuzzell** [comment]
looks good, @jessb0t !
