### ISSUE TITLE
scoring-ADEXI (part 2)

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#5]
Update ADEXI scoring mechanism to account for partial responses.

@georgebuzzell: Please add details.

**Comment by georgebuzzell** [comment]
@jessb0t @SDOsmany @F-said Here is the basic algorithm to address missing data for any scores that involve computing an average (unless a particular questionnaire has its own, distinct mechanism that the authors recommend instead). However, this method CAN NOT be used for a questionnaire that involves computing a sum score. An alternative method is needed for sum scores. 

1. For any AVERAGE score (not sum scores), first, identify the items that are used to compute that score.
2. Identify how many of the items (for that score) are present, and compute a percentage complete value.
3. If the percentage complete is greater than or equal to 80% (e.g. 8 out of 10, 16 out of 20, etc) then compute that average score using the items available. However, if the percentage complete is less than 80%, then the score CAN NOT be completed. Note, however, that it is possible that for a given participant, for a given questionnaire, they might have enough items to calculate some scores, but not others, and that is OK. Compute any that you can.

Alternative method for questionnaires involving sum scores (e.g., ADEXI):

1. For any sum score (not average scores), first, identify the items that are used to compute that score.
2. Identify how many of the items (for that score) are present, and compute a percentage complete value.
3. If the percentage complete is greater than or equal to 80% (e.g. 8 out of 10, 16 out of 20, etc) then move on to step 4 to compute a prorated sum score using the items available. However, if the percentage complete is less than 80%, then the score CAN NOT be completed. Note, however, that it is possible that for a given participant, for a given questionnaire, they might have enough items to calculate some scores, but not others, and that is OK. Compute any that you can.
4.

**Comment by jessb0t** [comment]
Thank you, @georgebuzzell !  @SDOsmany, let me know if you have any questions.  I might suggest that we set up a couple of different paradigms in your testing data.  I could independently calculate these values (manually) as a way for us to crosscheck not just the script but our independent understanding of these instructions.  If our numbers did not align, we could request further clarification from George. :)

**Comment by jessb0t** [comment]
Closing with #13.
