### ISSUE TITLE
scoring-ius

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#51]
**Scoring instructions:**

One total summed score: 
`ius_scrd-total_sx_rx_ex`
 
Two subscores: 
`ius_scrd-pas_sx_rx_ex` (Prospective Anxiety Subscale) (sum of: 1, 2, 4, 5, 8, 9, 11)
`ius_scrd-ias_sx_rx_ex`   (Inhibitory Anxiety Subscale) (sum of: 3, 6, 7, 10, 12)

_To calculate partials:_ 

Calculate percentage complete: 
`ius_perc-total_sx_rx_ex`
`ius_perc-pas_sx_rx_ex`
`ius_perc-ias_sx_rx_ex`

Compute score/subscore. If equal to 1, compute score; otherwise do not compute score. 

Done Defines: 

- ius added to the scoring script on dev-script (OP/FS)

- ius added to dev-uploads (PDF, REDcap zip, readme) (JA/ALN)

**Comment by jessb0t** [comment]
@georgebuzzell Please take a look at the scoring in the issue description to confirm before we formalize it in the script.  Thank you! :pray:

**Comment by georgebuzzell** [comment]
looks great, @jessb0t ! Thank you!
