### ISSUE TITLE
scoring-rtq

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#55]
**Scoring instructions:**

No total score. 

Two subscores:
`rtq_scrd-art_sx_rx_ex` (Absence of Repetitive Thinking) (sum of: 2, 14, 18, 20)

`rtq_scrd-rnt_sx_rx_ex` (Repetitive Negative Thinking) (sum of: 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)

_To calculate partials_:

Calculate percentage complete:  
`rtq_perc-art_sx_rx_ex`
`rtq_perc-rnt_sx_rx_ex`

Compute score/subscore. If equal to 1, compute score; otherwise do not compute score.

Done Defined:

- rtq added to the scoring script on dev-script (OP/FS)

- rtq added to dev-uploads (PDF, REDCap zip, readme) (JA/ALN)

**Comment by jessb0t** [comment]
@georgebuzzell Please take a look at the scoring in the issue description to confirm before we formalize it in the script.  Thank you! :pray:

**Comment by georgebuzzell** [comment]
@jessb0t looks great!

**Comment by jessb0t** [comment]
Due to handling of combo questionnaire, all item numbers above are increased by 10 (to account for the first ten questions, which are the PANAS-N).
