### ISSUE TITLE
scoring-erq

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#61]
**Scoring Instructions:**
No total score.  Two subscores:
`erq_scrdCogRea_sx_rx_ex` (average of: 1, 3, 5, 7, 8, 10)
`erq_scrdExpSup_sx_rx_ex` (average of: 2, 4, 6, 9)

_To calculate partials:_
Calculate percentage complete (0-1) for each subscore:
`erq_percCogRea_sx_rx_ex`
`erq_percExpSup_sx_rx_ex`

If greater than or equal to 0.8, compute subscore.  If less than 0.8, do not compute subscore.

**Done Defined:**
- erq added to the scoring script
- erq added to repo (PDF, REDCap zip, REDCap PDF, readme)

**Comment by jessb0t** [comment]
@georgebuzzell Please confirm scoring instructions above. :pray:  Actual instrument does not specify sum v average.  I assumed this was an "average" scoring mechanism based on some other findings in Google searches.

**Comment by georgebuzzell** [comment]
@jessb0t confirming the scoring here, for the two subscales, as averages, with no total score.

**Comment by jessb0t** [comment]
Adding follow-up note that 2003 paper appears to use mean ratings:
![image.png](https://images.zenhubusercontent.com/6054b276e1e4e5cb58c9e577/e6340ca5-664a-4d49-9766-f0037b4655ce)
