### ISSUE TITLE
scoring-rmbi

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#7]
**Scoring Instructions:**

> Total scores are generated by summing all items after the negative (for BI) items have been reversed. Subscale scores may also be generated. Please refer to the [primary reference](https://www.academia.edu/17838810/Measuring_a_behaviorally_inhibited_temperament_style_Development_and_initial_validation_of_new_self-report_measures) for further details.

Link to instrument [here](https://drive.google.com/file/d/1z8qHs_pqghHx4TS4HWUHRobUpYqNQW5o/view?usp=sharing).

**Questions:**

1. Are there any subscales that the lab wants to use?

**Done Defined:**

- RMBI added to scoring script

**Comment by jessb0t** [comment]
@georgebuzzell  Please provide guidance on questions above.  Thanks!

**Comment by georgebuzzell** [comment]
For any survey, please always score all scales/subscales.

**Comment by jessb0t** [comment]
Thanks, @georgebuzzell!

@SDOsmany, see #6 for reverse scoring.  It appears that we have four subscales for the RMBI:

**Scored Columns**
non-approach: rmbi_scored-non_s1_r1_e1
fearful inhibition: rmbi_scored-inh_s1_r1_e1
risk avoidance: rmbi_scored-risk_s1_r1_e1
shyness and sensitivity: rmbi_scored-shy_s1_r1_e1

**Percentage Complete Columns**
non-approach: rmbi_per-complete-non_s1_r1_e1
fearful inhibition: rmbi_per-complete-inh_s1_r1_e1
risk avoidance: rmbi_per-complete-risk_s1_r1_e1
shyness and sensitivity: rmbi_per-complete-shy_s1_r1_e1

And, then, of course, the total columns:
rmbi_scored-total_s1_r1_e1
rmbi_per-complete-total_s1_r1_e1

**Comment by jessb0t** [comment]
@F-said Please note that our standard nomenclature has been updated since the instructions above, but they provide the necessary detail on which items > which subscores.

**Comment by jessb0t** [comment]
Updated (and more clear) scoring instructions for testing and creation of the readme:

Items that are reverse scored are marked with an *.

Subscores
rmbi_scrdInh_sX_rX_eX (sum of: 1, 6, 10, 16, 18)
rmbi_scrdNon_sX_rX_eX (sum of: 2, 4*, 5*, 9, 11*, 15*)
rmbi_scrdShy_sX_rX_eX (sum of: 3, 12, 14, 17)
rmbi_scrdRisk_sX_rX_eX (sum of: 7*, 8, 13*)
rmbi_scrdTotal_sX_rX_eX (sum of the four subscores above)

Threshold for scoring: 100%.
