### ISSUE TITLE
testing-tai

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#74]

**Comment by anaNDClab** [comment]
The scores calculated from the input file match the scores seen in the output file!

**Comment by jessb0t** [comment]
During testing, discovered that the methodology to create the REDCap survey prevents us from having an accurate threshold on whether a participant considered and answered all questions.  Pushing scoring to next release.  However, I have already updated the repo with a corrected version of the questionnaire.

**Comment by jessb0t** [comment]
Tested clean!
